server:
  port: 40997

spring:
  application:
    name: service-vod
  servlet:
    multipart:
      max-file-size: 20480000
      max-request-size: 20480000
  cloud:
    nacos:
      server-addr: localhost:8848

aliyun:
  vod:
    file:
      key-id:
      key-secret: