server:
  port: 40998
spring:
  application:
    name: service-oss
  profiles:
    active: dev
  servlet:
    multipart:
      max-file-size: 2048000
      max-request-size: 2048000
#阿里云oss
aliyun:
  oss:
    file:
      key-secret: 
      key-id: 
      bucket-name: dbdj1201-gol
      endpoint: oss-cn-beijing.aliyuncs.com
#multipart.maxFileSize：
#  128KB
#multipart.maxRequestSize=128KB
