server:
  port: 40998
spring:
  application:
    name: service-oss
  profiles:
    active: dev
  servlet:
    multipart:
      max-file-size: 2048000
      max-request-size: 2048000
  cloud:
    nacos:
      server-addr: 47.94.4.93:8848
#阿里云oss
aliyun:
  oss:
    file:
      key-id:
      key-secret:
      bucket-name: dbdj1201-gol
      endpoint: oss-cn-beijing.aliyuncs.com
